package net.minecraft.block;

import net.minecraft.Bootstrap;
import net.minecraft.resource.Identifier;

public class Blocks {
   public static final Block AIR;
   public static final Block STONE;
   public static final GrassBlock GRASS;
   public static final Block DIRT;
   public static final Block COBBLESTONE;
   public static final Block PLANKS;
   public static final Block SAPLING;
   public static final Block BEDROCK;
   public static final FlowingLiquidBlock FLOWING_WATER;
   public static final LiquidSourceBlock WATER;
   public static final FlowingLiquidBlock FLOWING_LAVA;
   public static final LiquidSourceBlock LAVA;
   public static final SandBlock SAND;
   public static final Block GRAVEL;
   public static final Block GOLD_ORE;
   public static final Block IRON_ORE;
   public static final Block COAL_ORE;
   public static final Block LOG;
   public static final Block LOG2;
   public static final AbstractLeavesBlock LEAVES;
   public static final AbstractLeavesBlock LEAVES2;
   public static final Block SPONGE;
   public static final Block GLASS;
   public static final Block LAPIS_ORE;
   public static final Block LAPIS_BLOCK;
   public static final Block DISPENSER;
   public static final Block SANDSTONE;
   public static final Block NOTEBLOCK;
   public static final Block BED;
   public static final Block POWERED_RAIL;
   public static final Block DETECTOR_RAIL;
   public static final PistonBaseBlock STICKY_PISTON;
   public static final Block WEB;
   public static final TallPlantBlock TALLGRASS;
   public static final DeadBushBlock DEADBUSH;
   public static final PistonBaseBlock PISTON;
   public static final PistonHeadBlock PISTON_HEAD;
   public static final Block WOOL;
   public static final MovingBlock MOVING_BLOCK;
   public static final FlowerBlock YELLOW_FLOWER;
   public static final FlowerBlock RED_FLOWER;
   public static final PlantBlock BROWN_MUSHROOM;
   public static final PlantBlock RED_MUSHROOM;
   public static final Block GOLD_BLOCK;
   public static final Block IRON_BLOCK;
   public static final SlabBlock DOUBLE_STONE_SLAB;
   public static final SlabBlock STONE_SLAB;
   public static final Block BRICKS;
   public static final Block TNT;
   public static final Block BOOKSHELF;
   public static final Block MOSSY_COBBLESTONE;
   public static final Block OBSIDIAN;
   public static final Block TORCH;
   public static final FireBlock FIRE;
   public static final Block MOB_SPAWNER;
   public static final Block OAK_STAIRS;
   public static final ChestBlock CHEST;
   public static final RedstoneWireBlock REDSTONE_WIRE;
   public static final Block DIAMOND_ORE;
   public static final Block DIAMOND_BLOCK;
   public static final Block CRAFTING_TABLE;
   public static final Block WHEAT;
   public static final Block FARMLAND;
   public static final Block FURNACE;
   public static final Block LIT_FURNACE;
   public static final Block STANDING_SIGN;
   public static final Block WOODEN_DOOR;
   public static final Block LADDER;
   public static final Block RAIL;
   public static final Block STONE_STAIRS;
   public static final Block WALL_SIGN;
   public static final Block LEVER;
   public static final Block STONE_PRESSURE_PLATE;
   public static final Block IRON_DOOR;
   public static final Block WOODEN_PRESSURE_PLATE;
   public static final Block REDSTONE_ORE;
   public static final Block LIT_REDSTONE_ORE;
   public static final Block UNLIT_REDSTONE_TORCH;
   public static final Block REDSTONE_TORCH;
   public static final Block STONE_BUTTON;
   public static final Block SNOW_LAYER;
   public static final Block ICE;
   public static final Block SNOW;
   public static final CactusBlock CACTUS;
   public static final Block CLAY;
   public static final SugarCaneBlock REEDS;
   public static final Block JUKEBOX;
   public static final Block FENCE;
   public static final Block PUMPKIN;
   public static final Block NETHERRACK;
   public static final Block SOUL_SAND;
   public static final Block GLOWSTONE;
   public static final PortalBlock NETHER_PORTAL;
   public static final Block LIT_PUMPKIN;
   public static final Block CAKE;
   public static final RepeaterBlock REPEATER;
   public static final RepeaterBlock POWERED_REPEATER;
   public static final Block TRAPDOOR;
   public static final Block MONSTER_EGG;
   public static final Block STONE_BRICKS;
   public static final Block BROWN_MUSHROOM_BLOCK;
   public static final Block RED_MUSHROOM_BLOCK;
   public static final Block IRON_BARS;
   public static final Block GLASS_PANE;
   public static final Block MELON_BLOCK;
   public static final Block PUMPKIN_STEM;
   public static final Block MELON_STEM;
   public static final Block VINE;
   public static final Block FENCE_GATE;
   public static final Block BRICK_STAIRS;
   public static final Block STONE_BRICK_STAIRS;
   public static final MyceliumBlock MYCELIUM;
   public static final Block LILY_PAD;
   public static final Block NETHER_BRICKS;
   public static final Block NETHER_BRICK_FENCE;
   public static final Block NETHER_BRICK_STAIRS;
   public static final Block NETHER_WART;
   public static final Block ENCHANTING_TABLE;
   public static final Block BREWING_STAND;
   public static final CauldronBlock CAULDRON;
   public static final Block END_PORTAL;
   public static final Block END_PORTAL_FRAME;
   public static final Block END_STONE;
   public static final Block DRAGON_EGG;
   public static final Block REDSTONE_LAMP;
   public static final Block LIT_REDSTONE_LAMP;
   public static final SlabBlock DOUBLE_WOODEN_SLAB;
   public static final SlabBlock WOODEN_SLAB;
   public static final Block COCOA;
   public static final Block SANDSTONE_STAIRS;
   public static final Block EMERALD_ORE;
   public static final Block ENDER_CHEST;
   public static final TripwireHookBlock TRIPWIRE_HOOK;
   public static final Block TRIPWIRE;
   public static final Block EMERALD_BLOCK;
   public static final Block SPRUCE_STAIRS;
   public static final Block BIRCH_STAIRS;
   public static final Block JUNGLE_STAIRS;
   public static final Block COMMAND_BLOCK;
   public static final BeaconBlock BEACON;
   public static final Block COBBLESTONE_WALL;
   public static final Block FLOWER_POT;
   public static final Block CARROTS;
   public static final Block POTATOES;
   public static final Block WOODEN_BUTTON;
   public static final SkullBlock SKULL;
   public static final Block ANVIL;
   public static final Block TRAPPED_CHEST;
   public static final Block LIGHT_WEIGHTED_PRESSURE_PLATE;
   public static final Block HEAVY_WEIGHTED_PRESSURE_PLATE;
   public static final ComparatorBlock COMPARATOR;
   public static final ComparatorBlock POWERED_COMPARATOR;
   public static final DaylightDetectorBlock DAYLIGHT_DETECTOR;
   public static final Block REDSTONE_BLOCK;
   public static final Block QUARTZ_ORE;
   public static final HopperBlock HOPPER;
   public static final Block QUARTZ_BLOCK;
   public static final Block QUARTZ_STAIRS;
   public static final Block ACTIVATOR_RAIL;
   public static final Block DROPPER;
   public static final Block STAINED_HARDENED_CLAY;
   public static final Block BARRIER;
   public static final Block IRON_TRAPDOOR;
   public static final Block HAY;
   public static final Block CARPET;
   public static final Block HARDENED_CLAY;
   public static final Block COAL_BLOCK;
   public static final Block PACKED_ICE;
   public static final Block ACACIA_STAIRS;
   public static final Block DARK_OAK_STAIRS;
   public static final Block SLIME;
   public static final DoublePlantBlock DOUBLE_PLANT;
   public static final StainedGlassBlock STAINED_GLASS;
   public static final StainedGlassPaneBlock STAINED_GLASS_PANE;
   public static final Block PRISMARINE;
   public static final Block SEA_LANTERN;
   public static final Block STANDING_BANNER;
   public static final Block WALL_BANNER;

   private static Block byId(String id) {
      return (Block)Block.REGISTRY.get(new Identifier(id));
   }

   static {
      if (!Bootstrap.isInitialized()) {
         throw new RuntimeException("Accessed Blocks before Bootstrap!");
      } else {
         AIR = byId("air");
         STONE = byId("stone");
         GRASS = (GrassBlock)byId("grass");
         DIRT = byId("dirt");
         COBBLESTONE = byId("cobblestone");
         PLANKS = byId("planks");
         SAPLING = byId("sapling");
         BEDROCK = byId("bedrock");
         FLOWING_WATER = (FlowingLiquidBlock)byId("flowing_water");
         WATER = (LiquidSourceBlock)byId("water");
         FLOWING_LAVA = (FlowingLiquidBlock)byId("flowing_lava");
         LAVA = (LiquidSourceBlock)byId("lava");
         SAND = (SandBlock)byId("sand");
         GRAVEL = byId("gravel");
         GOLD_ORE = byId("gold_ore");
         IRON_ORE = byId("iron_ore");
         COAL_ORE = byId("coal_ore");
         LOG = byId("log");
         LOG2 = byId("log2");
         LEAVES = (AbstractLeavesBlock)byId("leaves");
         LEAVES2 = (AbstractLeavesBlock)byId("leaves2");
         SPONGE = byId("sponge");
         GLASS = byId("glass");
         LAPIS_ORE = byId("lapis_ore");
         LAPIS_BLOCK = byId("lapis_block");
         DISPENSER = byId("dispenser");
         SANDSTONE = byId("sandstone");
         NOTEBLOCK = byId("noteblock");
         BED = byId("bed");
         POWERED_RAIL = byId("golden_rail");
         DETECTOR_RAIL = byId("detector_rail");
         STICKY_PISTON = (PistonBaseBlock)byId("sticky_piston");
         WEB = byId("web");
         TALLGRASS = (TallPlantBlock)byId("tallgrass");
         DEADBUSH = (DeadBushBlock)byId("deadbush");
         PISTON = (PistonBaseBlock)byId("piston");
         PISTON_HEAD = (PistonHeadBlock)byId("piston_head");
         WOOL = byId("wool");
         MOVING_BLOCK = (MovingBlock)byId("piston_extension");
         YELLOW_FLOWER = (FlowerBlock)byId("yellow_flower");
         RED_FLOWER = (FlowerBlock)byId("red_flower");
         BROWN_MUSHROOM = (PlantBlock)byId("brown_mushroom");
         RED_MUSHROOM = (PlantBlock)byId("red_mushroom");
         GOLD_BLOCK = byId("gold_block");
         IRON_BLOCK = byId("iron_block");
         DOUBLE_STONE_SLAB = (SlabBlock)byId("double_stone_slab");
         STONE_SLAB = (SlabBlock)byId("stone_slab");
         BRICKS = byId("brick_block");
         TNT = byId("tnt");
         BOOKSHELF = byId("bookshelf");
         MOSSY_COBBLESTONE = byId("mossy_cobblestone");
         OBSIDIAN = byId("obsidian");
         TORCH = byId("torch");
         FIRE = (FireBlock)byId("fire");
         MOB_SPAWNER = byId("mob_spawner");
         OAK_STAIRS = byId("oak_stairs");
         CHEST = (ChestBlock)byId("chest");
         REDSTONE_WIRE = (RedstoneWireBlock)byId("redstone_wire");
         DIAMOND_ORE = byId("diamond_ore");
         DIAMOND_BLOCK = byId("diamond_block");
         CRAFTING_TABLE = byId("crafting_table");
         WHEAT = byId("wheat");
         FARMLAND = byId("farmland");
         FURNACE = byId("furnace");
         LIT_FURNACE = byId("lit_furnace");
         STANDING_SIGN = byId("standing_sign");
         WOODEN_DOOR = byId("wooden_door");
         LADDER = byId("ladder");
         RAIL = byId("rail");
         STONE_STAIRS = byId("stone_stairs");
         WALL_SIGN = byId("wall_sign");
         LEVER = byId("lever");
         STONE_PRESSURE_PLATE = byId("stone_pressure_plate");
         IRON_DOOR = byId("iron_door");
         WOODEN_PRESSURE_PLATE = byId("wooden_pressure_plate");
         REDSTONE_ORE = byId("redstone_ore");
         LIT_REDSTONE_ORE = byId("lit_redstone_ore");
         UNLIT_REDSTONE_TORCH = byId("unlit_redstone_torch");
         REDSTONE_TORCH = byId("redstone_torch");
         STONE_BUTTON = byId("stone_button");
         SNOW_LAYER = byId("snow_layer");
         ICE = byId("ice");
         SNOW = byId("snow");
         CACTUS = (CactusBlock)byId("cactus");
         CLAY = byId("clay");
         REEDS = (SugarCaneBlock)byId("reeds");
         JUKEBOX = byId("jukebox");
         FENCE = byId("fence");
         PUMPKIN = byId("pumpkin");
         NETHERRACK = byId("netherrack");
         SOUL_SAND = byId("soul_sand");
         GLOWSTONE = byId("glowstone");
         NETHER_PORTAL = (PortalBlock)byId("portal");
         LIT_PUMPKIN = byId("lit_pumpkin");
         CAKE = byId("cake");
         REPEATER = (RepeaterBlock)byId("unpowered_repeater");
         POWERED_REPEATER = (RepeaterBlock)byId("powered_repeater");
         TRAPDOOR = byId("trapdoor");
         MONSTER_EGG = byId("monster_egg");
         STONE_BRICKS = byId("stonebrick");
         BROWN_MUSHROOM_BLOCK = byId("brown_mushroom_block");
         RED_MUSHROOM_BLOCK = byId("red_mushroom_block");
         IRON_BARS = byId("iron_bars");
         GLASS_PANE = byId("glass_pane");
         MELON_BLOCK = byId("melon_block");
         PUMPKIN_STEM = byId("pumpkin_stem");
         MELON_STEM = byId("melon_stem");
         VINE = byId("vine");
         FENCE_GATE = byId("fence_gate");
         BRICK_STAIRS = byId("brick_stairs");
         STONE_BRICK_STAIRS = byId("stone_brick_stairs");
         MYCELIUM = (MyceliumBlock)byId("mycelium");
         LILY_PAD = byId("waterlily");
         NETHER_BRICKS = byId("nether_brick");
         NETHER_BRICK_FENCE = byId("nether_brick_fence");
         NETHER_BRICK_STAIRS = byId("nether_brick_stairs");
         NETHER_WART = byId("nether_wart");
         ENCHANTING_TABLE = byId("enchanting_table");
         BREWING_STAND = byId("brewing_stand");
         CAULDRON = (CauldronBlock)byId("cauldron");
         END_PORTAL = byId("end_portal");
         END_PORTAL_FRAME = byId("end_portal_frame");
         END_STONE = byId("end_stone");
         DRAGON_EGG = byId("dragon_egg");
         REDSTONE_LAMP = byId("redstone_lamp");
         LIT_REDSTONE_LAMP = byId("lit_redstone_lamp");
         DOUBLE_WOODEN_SLAB = (SlabBlock)byId("double_wooden_slab");
         WOODEN_SLAB = (SlabBlock)byId("wooden_slab");
         COCOA = byId("cocoa");
         SANDSTONE_STAIRS = byId("sandstone_stairs");
         EMERALD_ORE = byId("emerald_ore");
         ENDER_CHEST = byId("ender_chest");
         TRIPWIRE_HOOK = (TripwireHookBlock)byId("tripwire_hook");
         TRIPWIRE = byId("tripwire");
         EMERALD_BLOCK = byId("emerald_block");
         SPRUCE_STAIRS = byId("spruce_stairs");
         BIRCH_STAIRS = byId("birch_stairs");
         JUNGLE_STAIRS = byId("jungle_stairs");
         COMMAND_BLOCK = byId("command_block");
         BEACON = (BeaconBlock)byId("beacon");
         COBBLESTONE_WALL = byId("cobblestone_wall");
         FLOWER_POT = byId("flower_pot");
         CARROTS = byId("carrots");
         POTATOES = byId("potatoes");
         WOODEN_BUTTON = byId("wooden_button");
         SKULL = (SkullBlock)byId("skull");
         ANVIL = byId("anvil");
         TRAPPED_CHEST = byId("trapped_chest");
         LIGHT_WEIGHTED_PRESSURE_PLATE = byId("light_weighted_pressure_plate");
         HEAVY_WEIGHTED_PRESSURE_PLATE = byId("heavy_weighted_pressure_plate");
         COMPARATOR = (ComparatorBlock)byId("unpowered_comparator");
         POWERED_COMPARATOR = (ComparatorBlock)byId("powered_comparator");
         DAYLIGHT_DETECTOR = (DaylightDetectorBlock)byId("daylight_detector");
         REDSTONE_BLOCK = byId("redstone_block");
         QUARTZ_ORE = byId("quartz_ore");
         HOPPER = (HopperBlock)byId("hopper");
         QUARTZ_BLOCK = byId("quartz_block");
         QUARTZ_STAIRS = byId("quartz_stairs");
         ACTIVATOR_RAIL = byId("activator_rail");
         DROPPER = byId("dropper");
         STAINED_HARDENED_CLAY = byId("stained_hardened_clay");
         BARRIER = byId("barrier");
         IRON_TRAPDOOR = byId("iron_trapdoor");
         HAY = byId("hay_block");
         CARPET = byId("carpet");
         HARDENED_CLAY = byId("hardened_clay");
         COAL_BLOCK = byId("coal_block");
         PACKED_ICE = byId("packed_ice");
         ACACIA_STAIRS = byId("acacia_stairs");
         DARK_OAK_STAIRS = byId("dark_oak_stairs");
         SLIME = byId("slime");
         DOUBLE_PLANT = (DoublePlantBlock)byId("double_plant");
         STAINED_GLASS = (StainedGlassBlock)byId("stained_glass");
         STAINED_GLASS_PANE = (StainedGlassPaneBlock)byId("stained_glass_pane");
         PRISMARINE = byId("prismarine");
         SEA_LANTERN = byId("sea_lantern");
         STANDING_BANNER = byId("standing_banner");
         WALL_BANNER = byId("wall_banner");
      }
   }
}
